# Generated by Django 2.1.2 on 2019-04-18 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20190418_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='date_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
