# Generated by Django 2.1.2 on 2019-05-23 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20190418_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='date_birth',
            field=models.DateField(blank=True, default='Не задано', null=True),
        ),
    ]
