# Generated by Django 2.1.2 on 2019-05-23 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20190523_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='date_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
