# Generated by Django 2.0.4 on 2018-07-17 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0004_auto_20180718_0227'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bullet',
            old_name='recommendation',
            new_name='step',
        ),
    ]
